name: Build Flutter APK

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
      - name: Get dependencies
        run: flutter pub get
      - name: Build APK
        run: flutter build apk --release
#      - name: Upload APK artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: app-release.apk
#          path: build/app/outputs/flutter-apk/app-release.apk
      - name: Upload APK assets
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
          tag: v0.0.${{ github.run_number }}
